Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'rest_framework'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'rest_framework'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Invalid HTTP_HOST header: 'api.olivera.tech'. You may need to add 'api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /users/user/create/
Invalid HTTP_HOST header: 'api.olivera.tech'. You may need to add 'api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /users/user/create/
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Invalid HTTP_HOST header: 'api.olivera.tech'. You may need to add 'api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /users/token/obtain/
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Invalid HTTP_HOST header: 'api.olivera.tech'. You may need to add 'api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /users/token/obtain/
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Invalid HTTP_HOST header: 'api.olivera.tech'. You may need to add 'api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /users/user/create/
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Invalid HTTP_HOST header: 'api.olivera.tech'. You may need to add 'api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /users/user/create/
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Invalid HTTP_HOST header: 'api.olivera.tech'. You may need to add 'api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Invalid HTTP_HOST header: 'api.olivera.tech'. You may need to add 'api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Internal Server Error: /users/token/obtain/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /users/token/obtain/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /users/token/obtain/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Internal Server Error: /users/token/obtain/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /users/token/obtain/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Internal Server Error: /users/user/create/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /users/user/create/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /users/user/create/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /users/user/create/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/olivgvne/api.olivera.tech/passenger_wsgi.py", line 1, in <module>
    from django_forms.wsgi import application
  File "/home/olivgvne/api.olivera.tech/django_forms/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/middleware/common.py", line 53, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    if not is_valid_path(request.path_info, urlconf):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/base.py", line 153, in is_valid_path
    return resolve(path, urlconf)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /users/token/obtain/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /users/token/obtain/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Invalid HTTP_HOST header: 'www.api.olivera.tech'. You may need to add 'www.api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /
Internal Server Error: /
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Invalid HTTP_HOST header: 'www.api.olivera.tech'. You may need to add 'www.api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /
Internal Server Error: /
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/middleware/common.py", line 53, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    if not is_valid_path(request.path_info, urlconf):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/base.py", line 153, in is_valid_path
    return resolve(path, urlconf)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Invalid HTTP_HOST header: 'www.api.olivera.tech'. You may need to add 'www.api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /
Internal Server Error: /
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /users/token/obtain/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Internal Server Error: /users/token/obtain/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/django_forms/urls.py", line 23, in <module>
    path('users/', include ('users.urls'))
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/olivgvne/api.olivera.tech/users/urls.py", line 3, in <module>
    from .views import ObtainTokenPairWithColorView, CustomUserCreate, HelloWorldView, UserInfoView, LogoutAndBlacklistRefreshTokenForUserView
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
he2giejnn7jzo5miqnpf
he2giejnn7jzo5miqnpf
Internal Server Error: /users/user/create/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: users_customuser.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 25, in post
    user = serializer.save()
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/olivgvne/api.olivera.tech/users/serializers.py", line 46, in create
    instance.save()
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 727, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 765, in save_base
    force_update, using, update_fields,
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw,
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: users_customuser.username
Internal Server Error: /users/user/create/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: users_customuser.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 25, in post
    user = serializer.save()
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/olivgvne/api.olivera.tech/users/serializers.py", line 46, in create
    instance.save()
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 727, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 765, in save_base
    force_update, using, update_fields,
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw,
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: users_customuser.username
Unauthorized: /users/token/obtain/
80sm1kkxksaybxo162r0
80sm1kkxksaybxo162r0
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/token/obtain/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Internal Server Error: /users/blacklist/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olivgvne/api.olivera.tech/users/views.py", line 52, in post
    token = RefreshToken(refresh_token)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework_simplejwt/tokens.py", line 47, in __init__
    self.verify()
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework_simplejwt/tokens.py", line 180, in verify
    self.check_blacklist()
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework_simplejwt/tokens.py", line 192, in check_blacklist
    raise TokenError(_('Token is blacklisted'))
rest_framework_simplejwt.exceptions.TokenError: Token is blacklisted
Bad Request: /users/token/obtain/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/token/refresh/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /api/payment-activation/
Unauthorized: /api/payment-activation/
Unauthorized: /api/payment-activation/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Unauthorized: /users/user-info/
Not Found: /
Not Found: /
Invalid HTTP_HOST header: 'www.api.olivera.tech'. You may need to add 'www.api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Invalid HTTP_HOST header: 'www.api.olivera.tech'. You may need to add 'www.api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Invalid HTTP_HOST header: 'www.api.olivera.tech'. You may need to add 'www.api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Unauthorized: /users/token/obtain/
0qlwaku8j4btcln447jv
0qlwaku8j4btcln447jv
0qlwaku8j4btcln447jv
0qlwaku8j4btcln447jv
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Unauthorized: /users/user-info/
Unauthorized: /users/token/refresh/
Unauthorized: /users/user-info/
Not Found: /robots.txt
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Invalid HTTP_HOST header: 'www.api.olivera.tech'. You may need to add 'www.api.olivera.tech' to ALLOWED_HOSTS.
Bad Request: /
Not Found: /
Not Found: /
Unauthorized: /users/user-info/
Not Found: /
t4o0ztz4pl6mzakdeb6c
Internal Server Error: /api/payment-activation/
Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: api_payment_activation.admin_confirmation_number

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/olivgvne/api.olivera.tech/api/views.py", line 47, in post
    payment_activation_form = serializer.save()
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 727, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 765, in save_base
    force_update, using, update_fields,
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw,
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/olivgvne/virtualenv/api.olivera.tech/3.7/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: api_payment_activation.admin_confirmation_number
